-- 1. Roles Table
CREATE TABLE IF NOT EXISTS roles (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Users Table
CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(36) PRIMARY KEY, -- UUID string generated by Node.js
    email VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role_id INT,
    is_active BOOLEAN DEFAULT TRUE,
    mfa_enabled BOOLEAN DEFAULT FALSE,
    mfa_secret VARCHAR(100),
    locked_until TIMESTAMP NULL DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE RESTRICT
);

-- 3. Employees Table (Demo)
CREATE TABLE IF NOT EXISTS employees (
    id VARCHAR(36) PRIMARY KEY, -- UUID string generated by Node.js
    user_id VARCHAR(36) UNIQUE,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    department VARCHAR(100),
    position VARCHAR(100),
    salary DECIMAL(12, 2) NOT NULL, -- Sensitive Information
    email VARCHAR(100) UNIQUE NOT NULL,
    phone VARCHAR(30),
    hire_date DATE NOT NULL,
    is_canary BOOLEAN DEFAULT FALSE, -- Flag for decoy monitoring
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

-- 4. Leave Requests Table (Demo)
CREATE TABLE IF NOT EXISTS leave_requests (
    id VARCHAR(36) PRIMARY KEY, -- UUID string generated by Node.js
    employee_id VARCHAR(36),
    leave_type VARCHAR(50) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(20) DEFAULT 'Pending',
    reason TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE,
    CONSTRAINT chk_status CHECK (status IN ('Pending', 'Approved', 'Rejected'))
);

-- 5. System Audit Logs (Immutable)
CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGSERIAL PRIMARY KEY,
    user_id VARCHAR(36),
    user_role VARCHAR(50) NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ip_address VARCHAR(45) NOT NULL,
    device_browser VARCHAR(255),
    location_country VARCHAR(100),
    location_city VARCHAR(100),
    request_path VARCHAR(255) NOT NULL,
    request_method VARCHAR(10) NOT NULL,
    records_accessed INT DEFAULT 0,
    action_type VARCHAR(50) NOT NULL, -- e.g., 'LOGIN_SUCCESS', 'SALARY_READ', 'EXPORT'
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

-- 6. Security Incidents Table
CREATE TABLE IF NOT EXISTS security_incidents (
    id VARCHAR(36) PRIMARY KEY, -- UUID string generated by Node.js
    detected_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_id VARCHAR(36),
    triggered_rules JSONB NOT NULL, -- Stored as JSONB in Postgres
    raw_evidence JSONB NOT NULL,    -- Stored as JSONB in Postgres
    risk_score INT NOT NULL,
    risk_level VARCHAR(10) NOT NULL,
    recommended_actions JSONB NOT NULL, -- Stored as JSONB in Postgres
    mitigation_executed BOOLEAN DEFAULT FALSE,
    status VARCHAR(20) DEFAULT 'Open',
    notes TEXT,
    resolved_by VARCHAR(36),
    resolved_at TIMESTAMP NULL DEFAULT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (resolved_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT chk_risk_score CHECK (risk_score BETWEEN 0 AND 100),
    CONSTRAINT chk_risk_level CHECK (risk_level IN ('Low', 'Medium', 'High')),
    CONSTRAINT chk_incident_status CHECK (status IN ('Open', 'Investigating', 'Resolved', 'False Positive'))
);

-- 7. Device Fingerprint White-list
CREATE TABLE IF NOT EXISTS user_devices (
    id VARCHAR(36) PRIMARY KEY,
    user_id VARCHAR(36),
    device_hash VARCHAR(64) NOT NULL,
    browser_family VARCHAR(50),
    os_family VARCHAR(50),
    last_used TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, device_hash),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Helper trigger function to update updated_at timestamps
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger for users.updated_at
DROP TRIGGER IF EXISTS update_users_updated_at ON users;
CREATE TRIGGER update_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

-- Helper trigger function to update last_used timestamps
CREATE OR REPLACE FUNCTION update_last_used_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.last_used = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger for user_devices.last_used
DROP TRIGGER IF EXISTS update_user_devices_last_used ON user_devices;
CREATE TRIGGER update_user_devices_last_used
BEFORE UPDATE ON user_devices
FOR EACH ROW
EXECUTE FUNCTION update_last_used_column();

-- Trigger function for Audit Log Immutability in PostgreSQL
CREATE OR REPLACE FUNCTION prevent_audit_modification()
RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'Audit log table is immutable. Modifications are strictly prohibited.';
END;
$$ LANGUAGE plpgsql;

-- Triggers for audit_logs prevent update/delete
DROP TRIGGER IF EXISTS prevent_audit_update ON audit_logs;
CREATE TRIGGER prevent_audit_update
BEFORE UPDATE ON audit_logs
FOR EACH ROW
EXECUTE FUNCTION prevent_audit_modification();

DROP TRIGGER IF EXISTS prevent_audit_delete ON audit_logs;
CREATE TRIGGER prevent_audit_delete
BEFORE DELETE ON audit_logs
FOR EACH ROW
EXECUTE FUNCTION prevent_audit_modification();

-- Initial Roles Seeding
INSERT INTO roles (id, name, description) VALUES 
(1, 'System Administrator', 'Full control over the HRIS environment and all privacy analytics settings.'),
(2, 'HR Manager', 'Access to employee management, leave processing, and sensitive salary details.'),
(3, 'HR Staff', 'Access to general employee directory and leave requests, salary information is masked.'),
(4, 'Employee', 'Access to personal profile and own leave management.')
ON CONFLICT (id) DO NOTHING;

-- Synchronize the roles serial sequence
SELECT setval(pg_get_serial_sequence('roles', 'id'), COALESCE(max(id), 1)) FROM roles;
